# Adapted from 
# https://github.com/jhipster/generator-jhipster-native/blob/6bec2dd7c852ce2b25686710b8ff45dbebb69fcf/generators/ci-cd/templates/github-native.yml.ejs
# https://github.com/oktadev/auth0-full-stack-java-example/blob/main/.github/workflows/publish.yml

name: Build Native

on: workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    name: Build native on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['25']
        include:
        - os: ubuntu-latest
          native-build-args: --verbose
          executable-suffix: ''
        - os: macos-latest
          native-build-args: --verbose
          executable-suffix: ''
        - os: windows-latest
          native-build-args: --verbose
          executable-suffix: '.exe'
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up GraalVM (Java ${{ matrix.java-version }})
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '${{ matrix.java-version }}'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Java version
        run: |
          java --version
          native-image --version
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven          
      - name: Build native images
        run: mvn -B "-Dnative.build-args=${{ matrix.native-build-args }}" "-Pnative,graaljs" native:compile
      - name: Test native images
        run: ./target/json-schema-validator-native-example${{ matrix.executable-suffix }}
      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: json-schema-validator-native-example-${{ matrix.os }}
          path: target/json-schema-validator-native-example${{ matrix.executable-suffix }}
      - name: Generate build reports (On Failure)
        run: |
          mvn surefire-report:report-only -Daggregate=true
        if: failure()
      - name: Archive build reports (On Failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: build-reports-${{ matrix.os }}
          path: 'target/site/'
